//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnglishDX
{
    using System;
    using System.Collections.Generic;
    
    public partial class Datum
    {
        public Datum()
        {
            this.Logs = new HashSet<Log>();
        }
    
        public int id { get; set; }
        public string Word { get; set; }
        public string Translate { get; set; }
        public string Example { get; set; }
        public int AllRightAnswers { get; set; }
        public int AllWrongAnswers { get; set; }
        public int LastRightAnswers { get; set; }
        public int AllAnswers { get; set; }
        public bool IsEasy { get; set; }
        public int Complexity { get; set; }
        public bool IsAnswered { get; set; }
        public Nullable<int> RandomNumber { get; set; }
        public string Tag { get; set; }
    
        public virtual ICollection<Log> Logs { get; set; }
    }
}
