//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnglishDX
{
    using System;
    using System.Collections.Generic;
    
    public partial class DayStat
    {
        public int ID { get; set; }
        public System.DateTime DateStat { get; set; }
        public int AnswerAll { get; set; }
        public int AnswerRight { get; set; }
        public int AnswerWrong { get; set; }
        public int CompleteToday { get; set; }
        public System.DateTime LastAnswerTime { get; set; }
        public int CompleteApproaches { get; set; }
    }
}
