//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnglishDX
{
    using System;
    using System.Collections.Generic;
    
    public partial class Duration
    {
        public int Id { get; set; }
        public System.DateTime StartDateTime { get; set; }
        public int AnsweredWrong { get; set; }
        public long DurationSeconds { get; set; }
    }
}
