//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnglishDX
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestResultInt
    {
        public int id { get; set; }
        public Nullable<int> idQuest { get; set; }
        public string WordQuest { get; set; }
        public Nullable<int> Result { get; set; }
        public Nullable<System.DateTime> dttm { get; set; }
    }
}
